# Generated by Django 4.1.3 on 2022-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("key", models.IntegerField()),
                ("Style", models.TextField()),
                ("Style_Key", models.IntegerField()),
                ("Brewery", models.TextField()),
                ("Description", models.TextField()),
                ("ABV", models.DecimalField(decimal_places=1, max_digits=10)),
                ("Ave_Rating", models.DecimalField(decimal_places=1, max_digits=10)),
                ("Min_IBU", models.IntegerField()),
                ("Max_IBU", models.IntegerField()),
                ("Astringency", models.IntegerField()),
                ("Body", models.IntegerField()),
                ("Alcohol", models.IntegerField()),
                ("Bitter", models.IntegerField()),
                ("Sweet", models.IntegerField()),
                ("Sour", models.IntegerField()),
                ("Salty", models.IntegerField()),
                ("Fruits", models.IntegerField()),
                ("Hoppy", models.IntegerField()),
                ("Spices", models.IntegerField()),
                ("Malty", models.IntegerField()),
            ],
        ),
    ]
