# Generated by Django 3.2.15 on 2023-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Style_Key', models.IntegerField()),
                ('ABV', models.IntegerField()),
                ('Min_IBU', models.IntegerField()),
                ('Max_IBU', models.IntegerField()),
                ('Astringency', models.IntegerField()),
                ('Body', models.IntegerField()),
                ('Alcohol', models.IntegerField()),
                ('Bitter', models.IntegerField()),
                ('Sweet', models.IntegerField()),
                ('Sour', models.IntegerField()),
                ('Salty', models.IntegerField()),
                ('Fruits', models.IntegerField()),
                ('Hoppy', models.IntegerField()),
                ('Spices', models.IntegerField()),
                ('Malty', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
