# Generated by Django 4.1.4 on 2022-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handling', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
