# Generated by Django 3.2.15 on 2022-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencesnippet',
            name='Alcohol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Astringency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Ave_Rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Average_IBU',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Bitter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Body',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Fruits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Hoppy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Malty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Max_IBU',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Min_IBU',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Salty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Sour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Spices',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Style_Key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencesnippet',
            name='Sweet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
