# Generated by Django 3.2.15 on 2023-01-09 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_beer', '0005_alter_preferencesnippet_predicted_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencesnippet',
            name='Style_Key',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
