# Generated by Django 3.2.15 on 2023-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_beer', '0006_alter_preferencesnippet_style_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencesnippet',
            old_name='ABV_value',
            new_name='ABV',
        ),
        migrations.AlterField(
            model_name='preferencesnippet',
            name='Style_Key',
            field=models.IntegerField(),
        ),
    ]
