# Generated by Django 3.2.15 on 2023-01-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_db', '0002_alter_beer_abv_alter_beer_ave_rating'),
        ('predict_beer', '0007_auto_20230109_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencesnippet',
            name='Average_IBU',
        ),
        migrations.AlterField(
            model_name='preferencesnippet',
            name='predicted_beer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='beer_db.beer'),
        ),
    ]
